const franchiseRoutes = {
  franchiseRequest: "/franchise/register",
  franchiseLogin: "/franchise/login",
  franchiseOtpVerify: "/franchise/verify",
  franchiseForgotPass: "/franchise/verifyEmail",
  franchiseResetPassword: "/franchise/resetPassword",
  resendOtp: "/franchise/resendOtp",
  getProfile: "/franchise/getProfile",
  updateProfile: "/franchise/updateProfile",
  updateAddress: "/franchise/updateAddress",
  updatePassword: "/franchise/updatePassword",
  addService: "/franchise/addService",
  deleteService: "/franchise/deleteService",
  setTime: "/franchise/setTime",
  editTime: "franchise/editTime",
  getBookings: "/franchise/getBookings",
  fetchBooking: "/franchise/getBooking",
  getUser: "/franchise/getFranchise",
  changeStatus: "/franchise/changeStatus",
  getService:"/franchise/getService",
  weeklyReport:"/franchise/weeklyReport",
  monthlyReport:"/franchise/monthlyReport",
  yearlyReport :"/franchise/yearlyReport", 
  getStats:"/franchise/getStats"
};
export default franchiseRoutes;
